version: '3.4'

volumes:
  redis-data:

services:
  redis:
    image: redis
    ports: 
      - 6379
    volumes: 
      - redis-data:/data
    logging:
      options:
        max-size: 50m

  bot:
    build:
      context: .
    links:
     - redis
    volumes:
     - .:/discourse-nachtigaller
    environment:
      REDIS_URL: "redis://redis:6379/nachtigaller"
      HUBOT_LOG_LEVEL: "debug"
      HUBOT_DISCOURSE_USERNAME: "username"
      HUBOT_DISCOURSE_KEY: "secret"
      HUBOT_DISCOURSE_SERVER: "https://discourse.example.org/"
    logging:
      options:
        max-size: 50m

     
