version: '3.4'

volumes:
  redis-data:

services:
  redis:
    image: redis
    ports: 
      - 6379
    volumes: 
      - redis-data:/data
    logging:
      options:
        max-size: 50m

  bot:
    image: node
    links:
     - redis
    volumes:
     - .:/starter
    working_dir: /starter
    environment:
      REDIS_URL: "redis://redis:6379/nachtigaller"
    command: bin/hubot -a discourse-adapter -n abdul_nachtigaller -d
    logging:
      options:
        max-size: 50m

     
