var sprintf = require("sprintf-js").sprintf;

const strings = {
	newemail_title: "[%(folder)s] %(subject)s",
	newemail_body: "Es gibt eine neue E-Mail von **%(address)s** mit dem Betreff **%(subject)s** im Ordner **%(folder)s**",
	notification_first_title: "Erinnerung an %(description)s",
	notification_first_body: "Ich soll dich/euch an **%(description)s** erinnern. Bitte gib Bescheid wenn das schon gemacht ist und sagt *erledigt*",
	notification_second_title: "%(attempt)i. Erinnerung an %(description)s",
	notification_second_body: "Ich habe leider noch immer nichts von dir/euch gehört, deswegen zum %(attempt)i. Mal die Erinnerung an %(description)s. Bitte gib Bescheid wenn das schon gemacht ist und sagt *erledigt*",
	subscribed_success: "Du hast das Postfach **%(mailbox)s** erfolgreich abonniert!",
	subscribed_fail: "Das Postfach **%(mailbox)s** kann ich leider nicht finden, versuch es noch einmal. Folgende Postfächer stehen dir zur Auswahl: \n\n* %(mailboxes)s",
	unsubscribed_fail: "Das Postfach **%(mailbox)s** kann ich leider nicht finden, versuch es noch einmal.",
	unsubscribed_notsubscribed: "Du hast das Postfach **%(mailbox)s** nicht abonniert.",
	unsubscribed_success: "Du bekommst jetzt keine Benachrichtigungen für das Postfach **%(mailbox)s** mehr!",
	subscribed: "Aktuell hast du folgende Postfächer abonniert: \n\n* %(subscriptions)s\n\nUm Postfächer abzubestellen schreib mir welches, z.B.: 'Inbox/Buchhaltung abbestellen'",
	subscribed_none: "Aktuell hast du keine Postfächer abonniert.",
	not_allowed: "Ich darf leider nicht mit dir sprechen, sagt der Flo",
	mailboxes: "Folgende Postfächer stehen dir zur Auswahl: \n\n* %(mailboxes)s\n\nUm in Zukunft bei neuen E-Mails benachrichtigt zu werden, sag mir einfach welches Postfach es sein soll, z.B.: 'Inbox/Buchhaltung abonnieren'\n\n",
	error: "Leider ist ein Fehler aufgetreten: %(error)s",
	hellos: ['Hi', 'Hallo', 'Ahoi', ':wave:', 'Einen wunderschönen guten Tag'],
	byes: ['Liebe Grüße', 'Alles Liebe', 'Ahoi', 'Solidarische Grüße', 'Tüdelü', ':kissing_heart:', 'Baba'],
	welcome_title: "Hallo %(username)s",	
	welcome: "Mein Name ist Prof. Dr. Abdul Nachtigaller und ich bin hier um dir geholfen zu werden. Wenn du etwas brauchst schreib mir einfach eine Nachricht. Folgende Möglichkeiten stehen dir dabei offen:\n\n* Du willst benachrichtigt werden wenn neue E-Mails ankommen: sag 'Postfächer'\n\nDas war's aktuell leider schon. Meine anderen 6 Gehirne schlafen noch.",	
	citation : [
		"Das Universum besteht aus sieben Regionen, Norden, Süden, Westen, Osten, Vorher, Nachher und Zuhause.",
		"Ein vertrauter Geruch lag in der Meeresbriese, wie von Feuern, die in der Ferne brennen, mit einem Hauch von Zimt darin. So riecht, wie gelegentlich schon erwähnt, das Abenteuer.",
		"Das Licht der Sterne, die du am Firmament siehst, ist Millionen, Milliarden Jahre alt...",
		"Das war kein Denken mehr und noch kein Träumen, es war eine Fähigkeit genau dazwischen, die er ganz unbescheiden 'Smeiken' nannte: nicht die Kunst sich zu erinnern,sondern die Kunst, die Erinnerung zu leben. - Gefunden auf: https://myzitate.de/walter-moers/Das war kein Denken mehr und noch kein Träumen, es war eine Fähigkeit genau dazwischen, die er ganz unbescheiden 'Smeiken' nannte: nicht die Kunst sich zu erinnern,sondern die Kunst, die Erinnerung zu leben.",
		"Das Leben ist zu kostbar, um es dem Schicksal zu überlassen.",
		"Getürmt aus Buch auf Buch,\nVerlassen und verflucht,\nGesäumt von toten Fenstern,\nBewohnt nur von Gespenstern.\nBefallen von Getier\nAus Leder und Papier,\nEin Ort aus Wahn und Schall,\nGenannt Schloss Schattenhall.",
		"'Es gibt einen Ort im Universum, an dem sich alle großen künstlerischen Ideen bündeln, sich aneinander reiben und neue erzeugen' sagte er jetzt mit leiser Stimme.\n'Die kreative Dichte dieses Ortes muß enorm sein - ein unsichtbarer Planet mit Meeren aus Musik, mit Flüssen aus purer Inspiration und mit Vulkanen, die Gedanken speien, umzuckt von Geistesblitzen.'",
		"'Tja', raunte der Vogel mit gesenkter Stimme. 'Das Leben ist eine wilde Reise! Gefährlich! Unvorhersehbar! Voller Überraschungen - selbst wenn du es damit verbringst, irgendwo auf einem Stuhl an ein und derselben Stelle sitzen zu bleiben.'",
		"Wissen Sie eigentlich, wie mühselig es für einen Schriftsteller ist, den gleichmäßigen Fluß seiner Erzählung aufrechtzuerhalten? Natürlich nicht, woher sollten Sie als bloßer Konsument das auch wissen? Für Sie ist der anstrengende Teil mit dem Gang in die Buchhandlung beendet, jetzt haben Sie sich mit einer Tasse heißer Honigmilch in Ihren Lieblingssessel gelümmelt, tauchen in in den Strom der von Meisterhand verwobenen Worte und Sätze und lassen sich von ihm von Kapitel zu Kapitel tragen. Aber vielleicht können Sie wenigstens einmal versuchen, sich vorzustellen, wie sehr dem Autor manchmal seine Charaktere, der Ereigniszwang, die Dialogroutine und die Beschreibungspflicht auf die Nerven gehen?",
		"Vieläugig starrte der Wald die Kinder aus seinen Astlöchern an. Ensel kam es vor, als habe er ohne Erlaubnis den Palast eines Zauberers betreten, in dem das Mobiliar belebt war und ihn heimlich beobachtete.",
		"Krete fing bereits an, sich zu langweilen. Das Innere des Waldes hatte sich als weniger märchenhaft erwiesen, als sie es sich vorgestellt hatte. Es gab keine Einhörner, die an Flußbiegungen zur Tränke gingen, keine verwunschenen Schlösser aus Glas, nicht mal eine Riesenbohnenranke, die in die Wolken ragte. Ja, da waren kleine fliegende Elfenwespen, aber die schwirrten im Hochsommer auch in Fhernhachingen herum.",
		"Ensel kniff die Augen zu schmalen Schlitzen zusammen, um auf seine Schwester den Eindruck der Unberechenbarkeit zu machen.",
		"Die Vielfarbigkeit der Buntbärenfelle gab der ganzen Szenerie einen malerischen Anstrich, den keine andere Gemeinde Zamoniens zu bieten hatte. Es war wie ein lebendiges Sinnbild der Harmonie vor dem beruhigenden Hintergrund des grünen Waldes.",
		"Aus diesem hier habe ich einen Hustensaft gemacht, der zwar nicht besonders gut gegen Husten hilft, aber wenn du ihn genommen hast, fangen deine Haare so schön an zu singen, dass du den Husten völlig vergisst.",
		"Oben ist unten und hässlich ist schön.\n(Motto der Ledermäuse)",
		"Er würde zum ersten Mal Sledwaya verlassen, seine Heimat eintauschen gegen die Welt.",
		"'Jedes Ding', flüsterte Eißpin, 'hat seinen Schatten. Der Schatten ist die dunkle Seite, die jedem innewohnt. Solange er an uns gekettet ist, ist er unser Sklave, aber sobald man die Schatten von Ihren Besitzern trennt, zeigen sie ihr wahres Wesen. Dann werden sie böse, wild und gefährlich.'",
		"'Gestatten: Mein Name ist Fjodor F. Fjodor, aber du kannst mich Fjodor nennen.' Echo wagte nicht, nach der Bedeutung des F's zwischen dem beiden Fjodors zu fragen. Vielleicht stand es für Fjodor.",
		"Das ist mächtig komisch, Herr Stadtschrecksenmeister. Macht ruhig Eure Scherze über einen, der mit einer Pfote im Grab steht, denn ich habe etwas übrig für schwarzen Humor. Seht mir aber bitte nach, dass ich darüber im Moment nicht lachen kann. Mir ist das Lachen im Hals stecken geblieben, und da habe ich es runtergeschluckt, weil ich so großen Hunger habe.",
		"'Du musst tun, was du nicht lassen kannst', sagte Fjodor und seufzte noch einemal tief. Der Schuhu sah Echo so lange mit seinem wässrigen Blick an, bis dem Krätzchen unbehaglich wurde. 'Aber du musst auch manchmal lassen, was du nicht tun kannst', fügte er geheimnisvoll hinzu.",
		"'Sag mal, was meinst du, wie weit die Sterne da oben von uns entfernt sind? Sind sie genauso weit weg wie der Mond, oder sind sie uns näher?'\n'Du meinst die Löcher im Himmel? Die hat der Mann im Mond mit seiner Mondnadel reingepiekst, damit die Sonne durchscheinen kann, die dahinter schläft.'",
		"'Hmm...', machte Fjodor. 'Was schätzt du, wie weit der Mond von uns entfernt ist?'\n'Das ist einfach', sagte Echo. 'Ungefähr so weit wie die Berge da hinten.'\nDer Schuhu sah Echo lange an.\n'Wie kommst du denn darauf?', fragte er schließlich.\n'Das am weitesten Entfernte, was ich sehen kann, sind die Berge. Der Mond hängt genau darüber - also ist er genauso weit entfernt wie die Berge.'\nDer Schuhu sah Echo wieder lange an. 'Das ist dein physikalisches Weltbild?', fragte er.\n'Na ja, ich bin kein universalgelehrter Schuhu, ich bin ein dummes Krätzchen. Ich weiß nur, was mein Frauchen mir erzählt oder aus Büchern vorgelesen hat, und die waren alle nicht sehr dick und hatten meistens Bilder von lustigen Tieren drin. Von Eißpin lerne ich vieles über die Alchimie, aber nichts über die Astronomie. Er forscht lieber im Kleinen.'\n'Verstehe', sagte Fjodor. 'Und wenn ich dir sage, dass der Mond ungefähr zwanzigtausendmal so weit von uns entfernt ist wie die Berge?'\n'Dann würde ich dich für einen ziemlichen Spinner halten. Keiner kann so weit gucken.'",
		"Dabei sah ich sie. DIE WEIßE FLEDERMAUS! Natürlich war es nicht die tote Kreatur aus meinem Zimmer, aber ich bin davon überzeugt, dass es wenigstens eine nahe Verwandte, ein Bruder oder eine Schwester von ihr war, die von ihr den Befehl aus dem Jenseits erhalten hatte mich in noch größere Schwierigkeiten zu bringen.",
		"Es klang so, als versuchten im Nachbarzimmer eine Horde Yetis mit den Möbeln zu musizieren.",
		"Jeder Buchling nimmt irgendwann den Charakter des Dichters an, den er auswendig lernt, das ist unvermeidlich. Das ist unser Schicksal. Von Natur aus sind wir leere Blätter, die beschrieben werden wollen, ohne eigene Persönlichkeit. Und dann nehmen wir immer mehr die Eigenschaften unserers Dichters an, bis wir komplexe Individuen geworden sind.",
		"[...] und die Nachtwürgeschlange die finale Erfahrung machte, mitten in der Nacht beim Würgen erwürgt zu werden.",
		"In tiefen, kalten, hohlen Räumen\nWo Schatten sich mit Schatten paaren\nWo alte Bücher Träume träumen\nVon Zeiten als sie Bäume waren\nWo Kohle Diamant gebiert\nMan weder Licht noch Gnade kennt\nDort ist's, wo jener Geist regiert\nDen man den Schattenkönig nennt.",
		"Bei einem Dichter klauen ist Diebstahl, bei vielen Dichtern klauen ist Recherche.\nZitat von Walter Moers",
		"Das Leben ist zu kurz, um es dem Schicksal zu überlassen.",
		"Lesen ist eine intelligente Methode, sich selber das Denken zu ersparen. [...]Schreiben ist der verzweifelte Versuch, der Einsamkeit etwas Würde abzuringen - und etwas Geld!",
		"Die Mittagsgespenster kamen aus dem asiatischen Raum und trieben ihr Unwesen am liebsten mittags. Sie sahen aus wie aus Papier geschnitten. Niemand wusste so recht etwas mit ihnen anzufangen, denn wenn einem tagsüber ein Gespenst erscheint, dann ist das nicht sehr beeindruckend, der ganze gruselige Aspekt geht flöten. Es ist eigentlich nur lästig, am helllichten Tag einen Geist in der Wohnung zu haben. Die Mittagsgespenster ließen sich dadurch aber nicht irritieren, und zogen ihren Hokuspokus auch dann ab, wenn man dabei unbeeindruckt sein Essen verspeiste.",
		"Schon von weitem hörte man dieses Geräusch, das nur sehr große Städte hervorbirngen können, einen Ton, der aus allen Tönen zugleich besteht, aus Stimmengewirr und Tiergeschrei, aus Glockengeläut und Geldgeklimper, aus Kinderlachen und Hammerschlägen, aus Besteckgeklapper und dem Zuknallen Tausender von Türen, aus Geborenwerden und Sterben zur gleichen Zeit - ein grandioses Rauschen, vom Leben selbst erzeugt.",
		"Wenn man ihm eine Wette anbot, konnte er einfach nicht widerstehen, egal wie hoch der Einsatz war oder wie niedrig die Chancen für ihn standen. Sagte man: 'Ich wette eine Millionen atlantische Pyras, dass du dich nicht traust, mit einer Glocke um den Hals durch einen Wald voller geräuschempfindlicher Werwölfe zu laufen', konnte man sicher sein, dass er schon unterwegs war zum nächsten Glockengeschäft.",
		"Merk dir eins: Ich bin überall da, wo du mich nicht erwartest, aber niemals da, wo du mich suchst.",
		"'Sag mal', forderte Professor Nachtigaller, 'was weißt du jetzt über Dunkelheit?'",
		"'Oh, wenn man einmal das Vorurteil überwunden hat, dass Dunkelheit nicht nur die Abwesenheit von Licht, sondern selbst Energie ist, dann ist eigentlich alles ganz einfach', hörte ich mich zu meinem eigenen Erstaunen fachsimpeln. 'Man muss nur lernen, Licht und Dunkelheit als gleichberechtigte Energiequellen zu behandeln.'\n'Genau das ist das Problem', hakte Nachtigaller ein. 'Es liegt daran, dass die Dunkelheit so einen schlechten Ruf hat! Sie wird immer mit unangenehmen Dingen verbunden, dabei ist sie einfach nur eine andere Form von Beleuchtung - nur dunkler eben! Wir brauchen sie genauso nötig wie das Licht. Ohne Dunkelheit würde alles verdorren, es gäbe keinen Schlaf, keine Erholung. Ohne Finsternis gäbe es keine Energie, kein Wachstum. Die Nacht gibt uns die Kraft, den Tag zu überstehen. Hast du dir schon einmal überlegt, wieso man sich morgens, nach einer durchschlafenen Nacht, so frisch und energiegeladen fühlt?'",
		"Groots physikalisches Weltbild war erschütternd primitiv.\n'Die Welt ist ein Brötchen, das in einem Eimer Wasser schwimmt!' behauptete er trotzig.\n'Und worauf steht der Eimer?' versuchte ich ihn auszutricksen.\n'Der Eimer steht auf dem Rücken der großen Putzfrau, die auf alle Zeiten das Universum bohnert', antwortete Groot selbstbewusst.\n'Und worauf in aller Welt steht das Universum, das die Putzfrau bohnert?'\n'Das Universum steht nicht, es liegt. Das Universum ist nämlich flach wie eine Scheibe Wurst', half Zille aus.\n'Und worauf, bitteschön, liegt dann die Scheibe Wurst?' Jetzt hatte ich ihn.\n'Natürlich auf dem Brötchen', antwortete Groot.",
		"Mit Barbaren konnte man einfach nicht vernünftig diskutieren.",
		"Da seine Eltern und Spielkameraden seine Schreiberei belächelten, fühlte er sich unverstanden und wandte sich in seinen Schriften an ein Publikum aus Geistern. Für diese Geister schneiderte, formte, baute, malte und erträumte er eine Welt, in der jedes Wort, jedes Gefühl, jede Kreatur, jedes Ereignis, jeder Buchstabe und jeder Zufall am richtigen Platz standen. Und wenn sie einmal fertig gebaut wäre, diese Welt, fertig geschrieben und von Schreibfehlern und Stilbüten gereinigt, dann würde es schon kommen, sein Publikum, und sie mit ihm bewohnen. Eine Geisterwelt würde es sein, gebaut von einem Geist und bewohnt von vielen anderen Geistern.",
		"Er konnte keine jagenden Wolken betrachten, ohne in ihnen die epische Geschichte eines Wolkenvolkes zu sehen. Kein rasendes Wasser ohne durchsichtige Märchengestalten darin. Keine Wiese, ohne dass ihm nicht gleich die Saga eines Geschlechtes von Grashalmen eingefallen wäre. Insekten umschwirrten ihn und erzählten ihm ihre kleinen Schicksale.",
		"'Mit welcher Hand schreibst du?' fragte er.\n'Mit der rechten.'\n'Und dabei ist noch nichts herausgekommen, das du für veröffentlichungswürdig hältst?'\n'Nicht wirklich.'\n'Dann schreibst du mit der falschen Hand.'\n'Was?'\n'Der poetische Fluß vom Gehirn wird fehlgeleitet. Deine rechte ist nicht deine Schreibhand. Du musst mit der linken schreiben.'\n'Aber das kann ich nicht. Ich habe mit rechts schreiben gelernt.'\n'Dann musst du es neu lernen.'\n'Muss ich das wirklich?'\n'Wenn du nicht mit der richtigen Schreibhand dichtest, dann wird das nie was. Es ist so, als würdest du mit den Füßen schreiben.'",
		"Ich ächzte. Das fing ja gut an. Ich musste erst mal schreiben lernen, um schreiben zu lernen.",
		"Ist es nicht absurd, dass einem die Erinnerung an gute Zeiten viel eher die Tränen in die Augen treibt als die an schlechte?",
		"Und so, wie mich damals das Geschnurre der Buchlinge in den Schlaf gewogen hatte, war es nun das Jammern von Untoten, das Gekicher von Haselhexen und das Gekreisch von Sirenengespenstern, das mich bald sanft entschlummern ließ. Haarige Hände liefen über den Fußboden und durchsichtige Fledermäuse umflatterten meinen Kopf, aber es war mir herzlich egal. Inmitten von all diesem eingebildeten Irrsin fiel ich in tiefen Schlaf.",
		"Dann riß ich mich wieder zusammen, auch weil eine einsam lachende Person etwas Verzweifeltes an sich hat.",
		"Schreib nie einen Roman aus der Perspektive einer Türklinke!",
		"Von den Sternen kommen wir, zu den Sternen gehen wir. Das Leben ist nur eine Reise in die Fremde.",
		"Ein Schluck Wasser und eine Handvoll geräucherter Insekten hatten genügt, um aus einem hoffnungslosen Wrack einen gutgelaunten Optimisten zu machen. Es ist nicht das Gehirn, das unser Bewußtsein bestimmt. Es ist der Magen.",
		"'Sie gehören tatsächlich zu denjenigen Träumern, die glauben, alle Antworten stünden in Büchern, nicht wahr? Aber Bücher sind nicht grundsätzlich hilfreich und gut. Sie können sogar ausgesprochen bösartig sein. Haben Sie jemals etwas von den Gefährlichen Büchern gehört? Manche von ihnen töten schon durch die kleinste Berührung.'\nDann wurde mir schwarz vor Augen.",
		"'Eins noch Junge, was du dir merken musst: Es kommt nicht darauf an, wie eine Geschichte anfängt. Auch nicht darauf wie sie aufhört. Sondern auf das, was dazwischen passiert.'",
		"Die Neugier ist die mächtigste Antriebskraft im Universum, weil sie die beiden größten Bremskräfte im Universum überwinden kann: die Vernunft und die Angst."	
		]	
}


exports._t = function(key, p=undefined) {
	if (Array.isArray(strings[key])) {
		return strings[key][Math.floor(Math.random() * strings[key].length)];
	} else {
		return sprintf(strings[key],p);
	}
	
};